vim.keymap.set("n", "q", ":quit<CR>", { silent = true, noremap = true, buffer = 0, nowait = true })
vim.keymap.set("n", "f", "<C-f>", { silent = true, noremap = true, buffer = 0, nowait = true })
vim.keymap.set("n", "b", "<C-b>", { silent = true, noremap = true, buffer = 0, nowait = true })
vim.keymap.set("n", "u", "<C-u>", { silent = true, noremap = true, buffer = 0, nowait = true })
vim.keymap.set("n", "d", "<C-d>", { silent = true, noremap = true, buffer = 0, nowait = true })
